brew:
  packages:
    - zoxide
    - ghostty
    - bat
    - gh
    - rust
    - mise
    - direnv
    - fish
    - orbstack
    - fontconfig
    - libyaml
    - coreutils
  
  casks:
    - nikitabobko/tap/aerospace
    - github
    - visual-studio-code
    - raycast
    - keycastr

applications:
  - name: 1Password
    path: /Applications/1Password.app
    brew_cask: 1password
    cli_tap: 1password/tap/1password-cli
  
  - name: Arc
    path: /Applications/Arc.app
    brew_cask: arc