dotfiles_repo: https://github.com/QWYNG/dotfiles.git

home_paths:
  fish_config_dir: ~/.config/fish
  fish_config_file: ~/.config/fish/config.fish
  fish_functions_dir: ~/.config/fish/functions
  gitconfig: ~/.gitconfig
  aerospace_config: ~/.aerospace.toml
  zprofile: ~/.zprofile

application_paths:
  ghostty_config_dir: ~/Library/Application Support/com.mitchellh.ghostty/
  ghostty_config_file: ~/Library/Application Support/com.mitchellh.ghostty/config

dotfiles_sources:
  fish_config: files/fish/config.fish
  fish_functions: files/fish/functions
  ghostty_config: files/ghostty/config
  aerospace_config: files/aerospace/.aerospace.toml
  git_config: files/git/.gitconfig
  starship_config: files/starship/starship.toml
