name: Test Setup Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-setup:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run setup script
      id: setup
      env:
        DEBUG: true
        CI: true
        NONINTERACTIVE: true
      run: |
        cd ${{ github.workspace }}
        chmod +x bin/setup
        ./bin/setup 2>&1 | tee setup_output.log

    - name: Check for success message
      run: |
        if grep -q "All Steps Complete!" setup_output.log; then
          echo "✅ Setup completed successfully!"
          exit 0
        else
          echo "❌ Setup did not complete successfully"
          echo "--- Setup output ---"
          cat setup_output.log
          exit 1
        fi

    - name: Upload setup log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: setup-log
        path: setup_output.log
        retention-days: 7
